## 1. Datatypes

In [8]:
# Import pandas
#CODE HERE
import pandas as pd

In [ ]:
# Create a series of three different colours
#CODE HERE
color = pd.Series(["Teal", "Green", "Red"])
color

0     Teal
1    Green
2      Red
dtype: object

In [10]:
# View the series of different colours
#CODE HERE
color

0     Teal
1    Green
2      Red
dtype: object

In [13]:
# Create a series of three different car types and view it
#CODE HERE
cars = pd.Series(["BMW", "Toyota", "Honda"])
cars

0       BMW
1    Toyota
2     Honda
dtype: object

In [12]:
# Combine the Series of cars and colours into a DataFrame
#CODE HERE
cars

0       BMW
1    Toyota
2     Honda
dtype: object

### 2. Describe data

In [20]:
# Import data from Github and turn it into a DataFrame
car_sales = pd.read_csv("https://raw.githubusercontent.com/TipGreenTea/ITDS251x2-ML/main/car-sales.csv")
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [15]:
# Find the different datatypes of the car data DataFrame
#CODE HERE
car_sales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price            object
dtype: object

In [22]:
# Describe your current car sales DataFrame using describe()
#CODE HERE
car_sales.describe()

       Odometer (KM)      Doors
count      10.000000  10.000000
mean    78601.400000   4.000000
std     61983.471735   0.471405
min     11179.000000   3.000000
25%     35836.250000   4.000000
50%     57369.000000   4.000000
75%     96384.500000   4.000000
max    213095.000000   5.000000

In [23]:
# Get information about your DataFrame using info()
#CODE HERE
car_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Make           10 non-null     object
 1   Colour         10 non-null     object
 2   Odometer (KM)  10 non-null     int64
 3   Doors          10 non-null     int64
 4   Price          10 non-null     object
dtypes: int64(2), object(3)
memory usage: 532.0+ bytes

In [29]:
# List out all the column names of the car sales DataFrame
#CODE HERE
car_sales.columns
car_columns = car_sales.columns
car_columns

Index(['Make', 'Colour', 'Odometer (KM)', 'Doors', 'Price'], dtype='object')

In [30]:
# Find the length of the car sales DataFrame
#CODE HERE
len(car_sales)

10

## 3. Viewing and selecting data

In [31]:
# Show the first 5 rows of the car sales DataFrame
#CODE HERE
car_sales.head(5)

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00

In [32]:
# Show the bottom 5 rows of the car sales DataFrame
#CODE HERE
car_sales.tail(5)

     Make Colour  Odometer (KM)  Doors      Price
5  Toyota  Green          99213      4  $4,500.00
6   Honda   Blue          45698      4  $7,500.00
7   Honda   Blue          54738      4  $7,000.00
8  Toyota  White          60000      4  $6,250.00
9  Nissan  White          31600      4  $9,700.00

In [34]:
# Use .loc to select the row at index 3 of the car sales DataFrame
#CODE HERE
car_sales.loc[3]

Make                    BMW
Colour                Black
Odometer (KM)         11179
Doors                     5
Price            $22,000.00
Name: 3, dtype: object

In [36]:
# Use .iloc to select the row at position 3 of the car sales DataFrame
#CODE HERE
car_sales.iloc[3]

Make                    BMW
Colour                Black
Odometer (KM)         11179
Doors                     5
Price            $22,000.00
Name: 3, dtype: object

If you want to select a particular column, you can use `DataFrame.['COLUMN_NAME']`.

In [37]:
# Select the "Odometer (KM)" column from the car sales DataFrame
#CODE HERE
car_sales["Odometer (KM)"]

0    150043
1     87899
2     32549
3     11179
4    213095
5     99213
6     45698
7     54738
8     60000
9     31600
Name: Odometer (KM), dtype: int64

In [42]:
# Find the mean of the "Odometer (KM)" column in the car sales DataFrame
#CODE HERE
car_sales["Odometer (KM)"].mean()

np.float64(78601.4)

In [45]:
# Select the rows with over 100,000 kilometers on the Odometer
#CODE HERE
car_sales[car_sales["Odometer (KM)"] > 100000]

     Make Colour  Odometer (KM)  Doors      Price
0  Toyota  White         150043      4  $4,000.00
4  Nissan  White         213095      4  $3,500.00

In [46]:
# Create a crosstab of the Make and Doors columns
#CODE HERE
pd.crosstab(car_sales["Make"], car_sales["Doors"])

Doors   3  4  5
Make
BMW     0  0  1
Honda   0  3  0
Nissan  0  2  0
Toyota  1  3  0

In [52]:
# Group columns of the car sales DataFrame by the Make column and find the mean
#CODE HERE
car_sales.groupby("Make").mean(numeric_only=True)

        Odometer (KM)  Doors
Make
BMW      11179.000000   5.00
Honda    62778.333333   4.00
Nissan  122347.500000   4.00
Toyota   85451.250000   3.75

## 4. Manipulating Data

Let's check out what a version of our car_sales DataFrame might look like with missing values.

In [53]:
car_sales_missing = pd.read_csv("https://raw.githubusercontent.com/TipGreenTea/ITDS251x2-ML/main/car-sales-missing-data%20.csv")
car_sales_missing

     Make Colour  Odometer  Doors    Price
0  Toyota  White  150043.0    4.0   $4,000
1   Honda    Red   87899.0    4.0   $5,000
2  Toyota   Blue       NaN    3.0   $7,000
3     BMW  Black   11179.0    5.0  $22,000
4  Nissan  White  213095.0    4.0   $3,500
5  Toyota  Green       NaN    4.0   $4,500
6   Honda    NaN       NaN    4.0   $7,500
7   Honda   Blue       NaN    4.0      NaN
8  Toyota  White   60000.0    NaN      NaN
9     NaN  White   31600.0    4.0   $9,700

Notice the missing values are represented as `NaN` in pandas DataFrames.

Let's try fill them.

In [54]:
# Fill the Odometer column missing values with the mean of the column inplace
car_sales_missing["Odometer"].fillna(car_sales_missing["Odometer"].mean(),
                                     inplace=True)

/tmp/ipython-input-1923984859.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  car_sales_missing["Odometer"].fillna(car_sales_missing["Odometer"].mean(),

In [55]:
# View the car sales missing DataFrame and verify the changes
car_sales_missing

     Make Colour       Odometer  Doors    Price
0  Toyota  White  150043.000000    4.0   $4,000
1   Honda    Red   87899.000000    4.0   $5,000
2  Toyota   Blue   92302.666667    3.0   $7,000
3     BMW  Black   11179.000000    5.0  $22,000
4  Nissan  White  213095.000000    4.0   $3,500
5  Toyota  Green   92302.666667    4.0   $4,500
6   Honda    NaN   92302.666667    4.0   $7,500
7   Honda   Blue   92302.666667    4.0      NaN
8  Toyota  White   60000.000000    NaN      NaN
9     NaN  White   31600.000000    4.0   $9,700

In [64]:
# Remove the rest of the missing data inplace
#CODE HERE
car_sales_missing.dropna(inplace=True)

In [65]:
# Verify the missing values are removed by viewing the DataFrame
car_sales_missing

     Make Colour       Odometer  Doors    Price
0  Toyota  White  150043.000000    4.0   $4,000
1   Honda    Red   87899.000000    4.0   $5,000
2  Toyota   Blue   92302.666667    3.0   $7,000
3     BMW  Black   11179.000000    5.0  $22,000
4  Nissan  White  213095.000000    4.0   $3,500
5  Toyota  Green   92302.666667    4.0   $4,500

We'll now start to add columns to our DataFrame.

In [66]:
# Create a "Seats" column where every row has a value of 5, using car_sales dataframe
# Then view the DataFrame
#CODE HERE
seats_column = pd.Series([5, 5, 5, 5, 5])

car_sales["Seats"] = seats_column
car_sales

     Make Colour  Odometer (KM)  Doors       Price  Seats
0  Toyota  White         150043      4   $4,000.00    5.0
1   Honda    Red          87899      4   $5,000.00    5.0
2  Toyota   Blue          32549      3   $7,000.00    5.0
3     BMW  Black          11179      5  $22,000.00    5.0
4  Nissan  White         213095      4   $3,500.00    5.0
5  Toyota  Green          99213      4   $4,500.00    NaN
6   Honda   Blue          45698      4   $7,500.00    NaN
7   Honda   Blue          54738      4   $7,000.00    NaN
8  Toyota  White          60000      4   $6,250.00    NaN
9  Nissan  White          31600      4   $9,700.00    NaN

In [67]:
# Change the Odometer values from kilometers to miles using a Lambda function, using car_sales dataframe
# Then view the DataFrame
#CODE HERE
car_sales["Odometer (Miles)"] = car_sales["Odometer (KM)"].apply(lambda x: x / 1.6)
car_sales

     Make Colour  Odometer (KM)  Doors       Price  Seats  Odometer (Miles)
0  Toyota  White         150043      4   $4,000.00    5.0         93776.875
1   Honda    Red          87899      4   $5,000.00    5.0         54936.875
2  Toyota   Blue          32549      3   $7,000.00    5.0         20343.125
3     BMW  Black          11179      5  $22,000.00    5.0          6986.875
4  Nissan  White         213095      4   $3,500.00    5.0        133184.375
5  Toyota  Green          99213      4   $4,500.00    NaN         62008.125
6   Honda   Blue          45698      4   $7,500.00    NaN         28561.250
7   Honda   Blue          54738      4   $7,000.00    NaN         34211.250
8  Toyota  White          60000      4   $6,250.00    NaN         37500.000
9  Nissan  White          31600      4   $9,700.00    NaN         19750.000